import type { ScaleDefinition } from '../types';

export const SCALES: ScaleDefinition[] = [
  // ── COGNICIÓN ──────────────────────────────────────────────
  {
    id: 'mmse',
    name: 'Mini-Mental State Examination',
    shortName: 'MMSE',
    category: 'Cognición',
    description: 'Cribado cognitivo global',
    maxScore: 30,
    timeEstimate: '7-10 min',
  },
  {
    id: 'moca',
    name: 'Montreal Cognitive Assessment',
    shortName: 'MoCA',
    category: 'Cognición',
    description: 'Deterioro cognitivo leve',
    maxScore: 30,
    timeEstimate: '10 min',
  },
  {
    id: 'minicog',
    name: 'Mini-Cog',
    shortName: 'Mini-Cog',
    category: 'Cognición',
    description: 'Cribado cognitivo breve',
    maxScore: 5,
    timeEstimate: '3-5 min',
  },
  {
    id: 'ad8',
    name: 'AD8 Dementia Screening Interview',
    shortName: 'AD8',
    category: 'Cognición',
    description: 'Cribado de demencia — informante',
    maxScore: 8,
    timeEstimate: '2 min',
  },
  {
    id: 'reloj',
    name: 'Test del Reloj',
    shortName: 'Test del reloj',
    category: 'Cognición',
    description: 'Cribado visuoespacial rápido',
    maxScore: 10,
    timeEstimate: '2-3 min',
  },
  {
    id: 'fab',
    name: 'Frontal Assessment Battery',
    shortName: 'FAB',
    category: 'Cognición',
    description: 'Evaluación frontal — 6 subtests',
    maxScore: 18,
    timeEstimate: '10 min',
  },
  {
    id: 'gds',
    name: 'Global Deterioration Scale / FAST',
    shortName: 'GDS-FAST',
    category: 'Cognición',
    description: 'Estadiaje de demencia',
    maxScore: '7F',
    timeEstimate: '3-5 min',
  },
  {
    id: 'cdr',
    name: 'Clinical Dementia Rating — SB',
    shortName: 'CDR-SB',
    category: 'Cognición',
    description: 'Estadiaje global de demencia',
    maxScore: 18,
    timeEstimate: '15-20 min',
  },

  // ── ÁNIMO Y CONDUCTA ───────────────────────────────────────
  {
    id: 'npi',
    name: 'Neuropsychiatric Inventory-Q',
    shortName: 'NPI-Q',
    category: 'Ánimo y conducta',
    description: 'Síntomas neuropsiquiátricos',
    maxScore: 36,
    timeEstimate: '5-8 min',
  },
  {
    id: 'cornell',
    name: 'Cornell Scale for Depression in Dementia',
    shortName: 'Cornell',
    category: 'Ánimo y conducta',
    description: 'Depresión en demencia',
    maxScore: 38,
    timeEstimate: '10 min',
  },
  {
    id: 'phq9',
    name: 'Patient Health Questionnaire-9',
    shortName: 'PHQ-9',
    category: 'Ánimo y conducta',
    description: 'Cribado y gravedad de depresión',
    maxScore: 27,
    timeEstimate: '3-5 min',
  },

  // ── FRAGILIDAD Y SUPERVIVENCIA ─────────────────────────────
  {
    id: 'frailvig',
    name: 'Índice FRAIL-VIG',
    shortName: 'FRAIL-VIG',
    category: 'Fragilidad y supervivencia',
    description: 'Fragilidad avanzada — Amblàs-Novellas 2017',
    maxScore: 10,
    timeEstimate: '3-5 min',
  },
  {
    id: 'frail',
    name: 'FRAIL Scale',
    shortName: 'FRAIL',
    category: 'Fragilidad y supervivencia',
    description: 'Cribado de fragilidad — 5 ítems',
    maxScore: 5,
    timeEstimate: '2-3 min',
  },
  {
    id: 'rockwood',
    name: 'Clinical Frailty Scale',
    shortName: 'CFS Rockwood',
    category: 'Fragilidad y supervivencia',
    description: 'Estadiaje clínico de fragilidad',
    maxScore: 9,
    timeEstimate: '2 min',
  },
  {
    id: 'walter',
    name: 'Índice de Walter',
    shortName: 'Walter',
    category: 'Fragilidad y supervivencia',
    description: 'Mortalidad al año post-hospitalización ≥70 años',
    maxScore: 12,
    timeEstimate: '2-3 min',
  },

  // ── FUNCIÓN ────────────────────────────────────────────────
  {
    id: 'barthelbasico',
    name: 'Índice de Barthel',
    shortName: 'Barthel',
    category: 'Función',
    description: 'Actividades básicas de la vida diaria',
    maxScore: 100,
    timeEstimate: '5 min',
  },
  {
    id: 'barthel',
    name: 'Índice de Barthel Modificado (Shah)',
    shortName: 'Barthel-Shah',
    category: 'Función',
    description: 'ABVD — versión modificada 5 niveles',
    maxScore: 100,
    timeEstimate: '5 min',
  },
  {
    id: 'lawton',
    name: 'Lawton-Brody',
    shortName: 'Lawton',
    category: 'Función',
    description: 'Actividades instrumentales',
    maxScore: 8,
    timeEstimate: '3-5 min',
  },

  // ── MOVILIDAD ──────────────────────────────────────────────
  {
    id: 'sppb',
    name: 'Short Physical Performance Battery',
    shortName: 'SPPB',
    category: 'Movilidad',
    description: 'Rendimiento físico inferior',
    maxScore: 12,
    timeEstimate: '10-15 min',
  },
  {
    id: 'tinetti',
    name: 'Test de Tinetti',
    shortName: 'Tinetti',
    category: 'Movilidad',
    description: 'Equilibrio y marcha',
    maxScore: 28,
    timeEstimate: '10 min',
  },
  {
    id: 'tug',
    name: 'Timed Up and Go',
    shortName: 'TUG',
    category: 'Movilidad',
    description: 'Movilidad funcional cronometrada',
    maxScore: 0,
    timeEstimate: '2 min',
  },
  {
    id: 'alusti',
    name: 'Test Alusti',
    shortName: 'Alusti',
    category: 'Movilidad',
    description: 'Movilidad funcional — versión completa',
    maxScore: 100,
    timeEstimate: '10-15 min',
  },
  {
    id: 'alustiabrev',
    name: 'Test Alusti abreviado',
    shortName: 'Alusti Abrev.',
    category: 'Movilidad',
    description: 'Movilidad funcional — versión abreviada',
    maxScore: 50,
    timeEstimate: '5 min',
  },
  {
    id: 'velocidadmarcha',
    name: 'Velocidad de marcha 6 metros',
    shortName: 'VM 6m',
    category: 'Movilidad',
    description: 'Velocidad de marcha con cronómetro',
    maxScore: 0,
    timeEstimate: '2 min',
  },

  // ── ENFERMERÍA ─────────────────────────────────────────────
  {
    id: 'mnasf',
    name: 'Mini Nutritional Assessment SF',
    shortName: 'MNA-SF',
    category: 'Enfermería',
    description: 'Cribado de malnutrición',
    maxScore: 14,
    timeEstimate: '3-5 min',
  },
  {
    id: 'npuap',
    name: 'Clasificación NPUAP/EPUAP',
    shortName: 'NPUAP',
    category: 'Enfermería',
    description: 'Estadiaje de úlceras por presión',
    maxScore: 6,
    timeEstimate: '1 min',
  },
  {
    id: 'painad',
    name: 'Pain Assessment in Advanced Dementia',
    shortName: 'PAINAD',
    category: 'Enfermería',
    description: 'Dolor en demencia avanzada',
    maxScore: 10,
    timeEstimate: '5 min',
  },
  {
    id: 'ramsay',
    name: 'Escala de Ramsay',
    shortName: 'Ramsay',
    category: 'Enfermería',
    description: 'Nivel de sedación — 6 niveles',
    maxScore: 6,
    timeEstimate: '1 min',
  },
  {
    id: '4at',
    name: 'Test 4AT',
    shortName: '4AT',
    category: 'Enfermería',
    description: 'Cribado rápido de delirium',
    maxScore: 12,
    timeEstimate: '2 min',
  },
  {
    id: 'vvst',
    name: 'Volume-Viscosity Swallow Test',
    shortName: 'V-VST',
    category: 'Enfermería',
    description: 'Valoración clínica de disfagia',
    maxScore: 0,
    timeEstimate: '10-15 min',
  },

  // ── CUIDADOR ───────────────────────────────────────────────
  {
    id: 'zarit',
    name: 'Escala de Zarit',
    shortName: 'Zarit',
    category: 'Cuidador',
    description: 'Sobrecarga del cuidador principal',
    maxScore: 88,
    timeEstimate: '5-8 min',
  },
];

export const SCALE_MAP = Object.fromEntries(SCALES.map((s) => [s.id, s]));
